### ISSUE TITLE
deprecate this in favour of adding reader to `napari-btrack` plugin?

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/napari-btrack-reader#3]

**Comment by dstansby** [comment]
As per our discussion a couple of weeks ago, I think we could and should merge this into `BayesianTracker` itself as an "optional" sub-module that enables the reader when `napari` is installed. I'll take a go at this.

**Comment by paddyroddy** [comment]
Looks like this (the transferring) has already been done. Closing
