### ISSUE TITLE
Deprecate this package

### ISSUE THREAD

**Issue by dstansby** [lowe-lab-ucl/napari-btrack-reader#4]
Once https://github.com/quantumjot/BayesianTracker/pull/115 is merged and released, this package should be deprecated. In terms of tasks to do here that would involve:

- [ ] Removing `napari-btrack-reader` from the napari hub, by opening an issue at https://github.com/chanzuckerberg/napari-hub requesting removal
- [x] It's not possible to remove a package from PyPi, so a new release of this package with all code removed should be released, that contains a single deprecation warning when the package is imported, telling users that functionality has moved to `btrack`.
- [x] This repository should be set to "archived"

**Comment by paddyroddy** [comment]
Issue raised in chanzuckerberg/napari-hub#920

**Comment by paddyroddy** [comment]
The package has been now been deprecated from PyPI in quantumjot/btrack#256

**Comment by paddyroddy** [comment]
I'm going to archive the repo now. The bit from napari hub needs actioning, but we're waiting on them. Will leave this issue open.

**Comment by paddyroddy** [comment]
Now tracking in lowe-lab-ucl/napari-btrack#22
